-- Useful type definitions go here.

---@alias obsidian.CommandArgs vim.api.keyset.create_user_command.command_args

---@class obsidian.InsertTemplateContext
---The table passed to user substitution functions when inserting templates into a buffer.
---
---@field type "insert_template"
---@field template_name string|obsidian.Path The name or path of the template being used.
---@field template_opts obsidian.config.TemplateOpts The template options being used.
---@field templates_dir obsidian.Path|? The folder containing the template file.
---@field location [integer, integer, integer, integer] `{ buf, win, row, col }` location from which the request was made.
---@field partial_note? obsidian.Note An optional note with fields to copy from.

---@class obsidian.CloneTemplateContext
---The table passed to user substitution functions when cloning template files to create new notes.
---
---@field type "clone_template"
---@field template_name string|obsidian.Path The name or path of the template being used.
---@field template_opts obsidian.config.TemplateOpts The template options being used.
---@field templates_dir obsidian.Path|? The folder containing the template file.
---@field destination_path obsidian.Path The path the cloned template will be written to.
---@field partial_note obsidian.Note The note being written.

---@alias obsidian.TemplateContext obsidian.InsertTemplateContext | obsidian.CloneTemplateContext
---The table passed to user substitution functions. Use `ctx.type` to distinguish between the different kinds.

---@class obsidian.config
---@field workspaces obsidian.workspace.WorkspaceSpec[]
---@field log_level? integer
---@field notes_subdir? string
---@field templates? obsidian.config.TemplateOpts
---@field new_notes_location? obsidian.note.NewNotesLocation
---@field note_id_func? (fun(title: string|?, path: obsidian.Path|?): string)|?
---@field note_path_func? fun(spec: { id: string, dir: obsidian.Path, title: string|? }): string|obsidian.Path
---@field frontmatter? obsidian.config.FrontmatterOpts
---@field backlinks? obsidian.config.BacklinkOpts
---@field completion? obsidian.config.CompletionOpts
---@field picker? obsidian.config.PickerOpts
---@field daily_notes? obsidian.config.DailyNotesOpts
---@field open_notes_in? obsidian.config.OpenStrategy
---@field ui? obsidian.config.UIOpts
---@field attachments? obsidian.config.AttachmentsOpts
---@field callbacks? obsidian.config.CallbackConfig
---@field legacy_commands? boolean
---@field statusline? obsidian.config.StatuslineOpts
---@field footer? obsidian.config.FooterOpts
---@field open? obsidian.config.OpenOpts
---@field checkbox? obsidian.config.CheckboxOpts
---@field comment? obsidian.config.CommentOpts
---@field search? obsidian.config.SearchOpts
---@field note? obsidian.config.NoteOpts
---@field link? obsidian.config.LinkOpts

---@class obsidian.config.Internal
---@field workspaces obsidian.workspace.WorkspaceSpec[]
---@field log_level integer
---@field notes_subdir string|?
---@field templates obsidian.config.TemplateOpts
---@field new_notes_location obsidian.note.NewNotesLocation
---@field note_id_func (fun(id: string|?, path: obsidian.Path|?): string)
---@field note_path_func (fun(spec: { id: string, dir: obsidian.Path }): string|obsidian.Path)
---@field frontmatter obsidian.config.FrontmatterOpts
---@field backlinks obsidian.config.BacklinkOpts
---@field completion obsidian.config.CompletionOpts
---@field picker obsidian.config.PickerOpts
---@field daily_notes obsidian.config.DailyNotesOpts
---@field open_notes_in obsidian.config.OpenStrategy
---@field ui obsidian.config.UIOpts
---@field attachments obsidian.config.AttachmentsOpts
---@field callbacks obsidian.config.CallbackConfig
---@field legacy_commands boolean
---@field statusline obsidian.config.StatuslineOpts
---@field footer obsidian.config.FooterOpts
---@field open obsidian.config.OpenOpts
---@field checkbox obsidian.config.CheckboxOpts
---@field comment obsidian.config.CommentOpts
---@field search obsidian.config.SearchOpts
---@field note obsidian.config.NoteOpts
---@field link obsidian.config.LinkOpts

---@alias obsidian.link.LinkFormat "shortest" | "relative" | "absolute"
---@alias obsidian.note.NewNotesLocation "current_dir" | "notes_subdir"
