-- Useful type definitions go here.

---@alias obsidian.CommandArgs vim.api.keyset.create_user_command.command_args

---@class obsidian.InsertTemplateContext
---The table passed to user substitution functions when inserting templates into a buffer.
---
---@field type "insert_template"
---@field template_name string|obsidian.Path The name or path of the template being used.
---@field template_opts obsidian.config.TemplateOpts The template options being used.
---@field templates_dir obsidian.Path The folder containing the template file.
---@field location [number, number, number, number] `{ buf, win, row, col }` location from which the request was made.
---@field partial_note? obsidian.Note An optional note with fields to copy from.

---@class obsidian.CloneTemplateContext
---The table passed to user substitution functions when cloning template files to create new notes.
---
---@field type "clone_template"
---@field template_name string|obsidian.Path The name or path of the template being used.
---@field template_opts obsidian.config.TemplateOpts The template options being used.
---@field templates_dir obsidian.Path The folder containing the template file.
---@field destination_path obsidian.Path The path the cloned template will be written to.
---@field partial_note obsidian.Note The note being written.

---@alias obsidian.TemplateContext obsidian.InsertTemplateContext | obsidian.CloneTemplateContext
---The table passed to user substitution functions. Use `ctx.type` to distinguish between the different kinds.

---@class obsidian.workspace.WorkspaceSpec
---
---@field path string|(fun(): string)|obsidian.Path|(fun(): obsidian.Path)
---@field name string|?
---@field strict boolean|? If true, the workspace root will be fixed to 'path' instead of the vault root (if different).
---@field overrides obsidian.config?

---@class obsidian.config
---@field workspaces obsidian.workspace.WorkspaceSpec[]
---@field log_level? integer
---@field notes_subdir? string
---@field templates? obsidian.config.TemplateOpts
---@field new_notes_location? obsidian.config.NewNotesLocation
---@field note_id_func? (fun(title: string|?, path: obsidian.Path|?): string)|?
---@field note_path_func? fun(spec: { id: string, dir: obsidian.Path, title: string|? }): string|obsidian.Path
---@field wiki_link_func? fun(opts: {path: string, label: string, id: string|?}): string
---@field markdown_link_func? fun(opts: {path: string, label: string, id: string|?}): string
---@field preferred_link_style? obsidian.config.LinkStyle
---@field follow_url_func? fun(url: string)
---@field follow_img_func? fun(img: string)
---@field note_frontmatter_func? (fun(note: obsidian.Note): table)
---@field disable_frontmatter? (fun(fname: string?): boolean)|boolean
---@field frontmatter? obsidian.config.FrontmatterOpts
---@field backlinks? obsidian.config.BacklinkOpts
---@field completion? obsidian.config.CompletionOpts
---@field picker? obsidian.config.PickerOpts
---@field daily_notes? obsidian.config.DailyNotesOpts
---@field weekly_notes? obsidian.config.WeeklyNotesOpts
---@field monthly_notes? obsidian.config.MonthlyNotesOpts
---@field quarterly_notes? obsidian.config.QuarterlyNotesOpts
---@field yearly_notes? obsidian.config.YearlyNotesOpts
---@field sort_by? obsidian.config.SortBy
---@field sort_reversed? boolean
---@field search_max_lines? integer
---@field open_notes_in? obsidian.config.OpenStrategy
---@field ui? obsidian.config.UIOpts | table<string, any>
---@field attachments? obsidian.config.AttachmentsOpts
---@field callbacks? obsidian.config.CallbackConfig
---@field legacy_commands? boolean
---@field statusline? obsidian.config.StatuslineOpts
---@field footer? obsidian.config.FooterOpts
---@field open? obsidian.config.OpenOpts
---@field checkbox? obsidian.config.CheckboxOpts
---@field comment? obsidian.config.CommentOpts
---@field search? obsidian.config.SearchOpts

---@class obsidian.config.Internal
---@field dir string|?
---@field workspaces obsidian.workspace.WorkspaceSpec[]|?
---@field log_level integer
---@field notes_subdir string|?
---@field templates obsidian.config.TemplateOpts
---@field new_notes_location obsidian.config.NewNotesLocation
---@field note_id_func (fun(id: string|?, path: obsidian.Path|?): string)|?
---@field note_path_func (fun(spec: { id: string, dir: obsidian.Path }): string|obsidian.Path)|?
---@field wiki_link_func (fun(opts: {path: string, label: string, id: string|?}): string)
---@field markdown_link_func (fun(opts: {path: string, label: string, id: string|?}): string)
---@field preferred_link_style obsidian.config.LinkStyle
---@field follow_url_func fun(url: string)|?
---@field follow_img_func fun(img: string)|?
---@field frontmatter obsidian.config.FrontmatterOpts
---@field backlinks obsidian.config.BacklinkOpts
---@field completion obsidian.config.CompletionOpts
---@field picker obsidian.config.PickerOpts
---@field daily_notes obsidian.config.DailyNotesOpts
---@field weekly_notes obsidian.config.WeeklyNotesOpts
---@field monthly_notes obsidian.config.MonthlyNotesOpts
---@field quarterly_notes obsidian.config.QuarterlyNotesOpts
---@field yearly_notes obsidian.config.YearlyNotesOpts
---@field sort_by obsidian.config.SortBy|?
---@field sort_reversed boolean|?
---@field search_max_lines integer
---@field open_notes_in obsidian.config.OpenStrategy
---@field ui obsidian.config.UIOpts | table<string, any>
---@field attachments obsidian.config.AttachmentsOpts
---@field callbacks obsidian.config.CallbackConfig
---@field legacy_commands boolean
---@field statusline obsidian.config.StatuslineOpts
---@field footer obsidian.config.FooterOpts
---@field open obsidian.config.OpenOpts
---@field checkbox obsidian.config.CheckboxOpts
---@field comment obsidian.config.CommentOpts
---@field search obsidian.config.SearchOpts
